---
# This playbook deploys a shipyard server

- hosts: shipyard-servers
  user: ansible
  sudo: yes
  
  roles:    
    - shipyard-base
    - shipyard-redis
    - shipyard-router
    - shipyard-lb
    - shipyard-db
    - shipyard-www
    
- hosts: shipyard-agents
  user: ansible
  sudo: yes
  
  roles:    
    - shipyard-agent